version: '3.4'
services:
  apache-proxy-certbot:
    image: httpd-proxy-certbot
    container_name: apache-proxy-certbot-cntnr
    build:
      context: './apache/'
      target: httpd-proxy-certbot
      args:
        DOMAIN: ${MY_DOMAIN_1}
        HTTPD_USER: ${HTTPD_USER}
    volumes:
      - ./www/:/var/www/html/
      # comment out the following line to use the included self-signed cert
      - ./certs/live/${MY_DOMAIN_1}/:/usr/local/apache2/tls/live/${MY_DOMAIN_1}
      - ./certs/archive/${MY_DOMAIN_1}/:/usr/local/apache2/tls/archive/${MY_DOMAIN_1}

      - ./apache/httpd-conf/:/usr/local/apache2/conf/extra/httpd-conf/
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
